Fix for Missing Class features
kakaroto/Beyond20 pull request #1165
Opened 2024-09-18 00:55 UTC by dmportella

Added fix for https://github.com/kakaroto/Beyond20/issues/1164

2024-09-18 00:59 UTC, dmportella commented
@kakaroto I will check the other features as time goes on and apply any patches to it, this was working until yesterday but I think they changed it recently

2024-09-18 17:32 UTC, kakaroto requested changes
Thanks for reporting and fixing this.
I've just been reviewing it and checking for any other changes needed or affected by this. 
The `featureDetailsToList` method is used though to capture the feature details of all character features: class features, racial traits and feats. It's also used to capture the actions list from the actions tab.
Your change only makes it find the class features, so it will break for the other stuff. I'd suggest the following change to the selector:
```js
const features = $(selector).find(".ct-feature-snippet > .ct-feature-snippet__heading, .ct-feature-snippet--class > div[class*='styles_heading'], .ct-feature-snippet--racial-trait > div[class*='styles_heading'], .ct-feature-snippet--feat > div[class*='styles_heading']")
```
I kept the original selector too because the ct-actions-list still uses the old classes...

However, I also noticed that the `updateFeatures` method below it will now fail to find racial traits because the div has no classes now instead of the `ct-race-detail` it had before 😭 
I've found that this can get us the div we want (line 259): 
```js
const race_detail = $(".ct-features .ct-content-group:has(.ct-feature-snippet--racial-trait)");
```
If you could review my proposed changed and test/confirm it works as expected, then let me know to approve the updated PR.

Thanks!
(by the way, are you in the Beyond20 discord?)

2024-09-18 18:57 UTC, dmportella reviewed
they work as you suggested <3

2024-09-18 18:57 UTC, dmportella commented on src/dndbeyond/base/character.js
> +        const features = $(selector).find(".ct-feature-snippet > .ct-feature-snippet__heading, .ct-feature-snippet--class > div[class*='styles_heading'], .ct-feature-snippet--racial-trait > div[class
Yep tested it and it all seem to work

2024-09-18 18:57 UTC, dmportella commented on src/dndbeyond/base/character.js
> +        const race_detail = $(".ct-features .ct-content-group:has(.ct-feature-snippet--racial-trait)");
yep this works well too

2024-09-18 18:59 UTC, dmportella commented
@kakaroto I tested the changes you suggested and they work well, I had not noticed the other features (it was a bit late at night when i did those changes) but good catch, I was not on the discord, but I have joined it now under the name gothyl

2024-09-18 19:01 UTC, dmportella commented
All changes are done as you suggested, i will check if there is any other issues, there is so many "features" on the website that only affect certain classes that takes some time to see what is suppose to happen

2024-09-18 19:38 UTC, kakaroto approved these changes
Thanks for testing and pushing the fix! LGTM!

2024-09-18 19:39 UTC, merged

2024-09-20 22:47 UTC, shazam2323 commented
I thought this was fixed? As of today it's still not working. My fire genie doesn't have genie's wrath showing

2024-09-21 21:08 UTC, kakaroto commented
> I thought this was fixed? As of today it's still not working. My fire genie doesn't have genie's wrath showing

It being fixed doesn't mean it's released and it doesn't mean your extension on your local PC has been updated.
I'll be releasing the update this weekend, then it can take a week or more before the new release is reviewed by the chrome/firefox/edge store teams and it becomes publicly available.
Either be patient, or read here on how to install the development version: https://github.com/kakaroto/Beyond20#developer-mode-installation